language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - curl http://repo.reverbrain.com/REVERBRAIN.GPG | apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install libcocaine-dev --force-yes
script:
  - npm run coveralls
